
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace AI_ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            AI.ModelInput sampleData = new AI.ModelInput()
            {
                ImageSource = @"D:\ImageForAI\Jenosu\%3F%3F%3F%3F%3F_-_%3F%3F%3F%3F%3F%3F%3F%3F%3F_%3F%3F%3F%3F%3F.jpg",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = AI.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");


            Console.WriteLine($"ImageSource: {@"D:\ImageForAI\Jenosu\%3F%3F%3F%3F%3F_-_%3F%3F%3F%3F%3F%3F%3F%3F%3F_%3F%3F%3F%3F%3F.jpg"}");


            Console.WriteLine($"\n\nPredicted Label value: {predictionResult.Prediction} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
